import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "@/components/Providers";
import Header from "@/components/Header";
import Navigation from "@/components/Navigation";
import Player from "@/components/Player";

const alegreya = localFont({
  src: "./fonts/Alegreya-Regular.ttf",
  variable: "--font-alegreya",
  // weight: "100 500",
});

const hkGrotesque = localFont({
  src: "./fonts/HKGrotesk-Bold.ttf",
  variable: "--font-hk-bold",
  weight: "100 900",
});

const ptSans = localFont({
  src: "./fonts/PTSans-Regular.ttf",
  variable: "--font-pt-sans",
  weight: "100 500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased" suppressHydrationWarning>
      <body
        className={`min-h-full ${ptSans.variable} ${hkGrotesque.variable} ${alegreya.variable}`}
      >
        <Providers>
          <div className="flex w-full min-h-screen">
            <Header />
            <main className="flex-auto ml-[28rem]">
              <Navigation />
              <div className="p-10 flex justify-center">
                <div className="w-[40rem]">{children}</div>
              </div>
            </main>
            <footer></footer>
            <div className="fixed p-2 bottom-0 left-0 w-[28rem]">
              <Player />
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
