import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "@/components/Providers";
import Player from "@/components/Player";

const alegreya = localFont({
  src: "./fonts/Alegreya-Regular.ttf",
  variable: "--font-alegreya",
  // weight: "100 500",
});

const hkGrotesque = localFont({
  src: "./fonts/HKGrotesk-Bold.ttf",
  variable: "--font-hk-bold",
  weight: "100 900",
});

const ptSans = localFont({
  src: "./fonts/PTSans-Regular.ttf",
  variable: "--font-pt-sans",
  weight: "100 500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased" suppressHydrationWarning>
      <body
        className={`min-h-full ${ptSans.variable} ${hkGrotesque.variable} ${alegreya.variable}`}
      >
        <svg
          className="pointer-events-none fixed isolate z-50 opacity-70 mix-blend-soft-light"
          width="100%"
          height="100%"
        >
          <filter id="noise">
            <feTurbulence
              type="fractalNoise"
              baseFrequency="0.80"
              numOctaves="4"
              stitchTiles="stitch"
            ></feTurbulence>
          </filter>
          <rect width="100%" height="100%" filter="url(#noise)"></rect>
        </svg>
        <Providers>
          <div className="flex w-full min-h-screen">
            {children}
            <footer></footer>
            <div className="fixed bottom-8 left-8 w-[26rem]">
              <Player />
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
// <Header />
